### ISSUE TITLE
希望增加微博登录有验证码情况的处理

### ISSUE THREAD

**Issue by skygongque** [CharlesPikachu/DecryptLogin#1]
- 我尝试了pc端https://login.sina.com.cn/signup/signin.php

- 我是手动处理处理验证码的，大佬若是可以自动识别就完美了

- 最核心的post请求的一些常见retcode，'101' 用户名或密码不正确，'4049' 需要验证码 '2070' 验证码错误 

- prelogin的get请求和ssologin_url的post请求的返回可以是json数据这样取值更方便

**Comment by CharlesPikachu** [comment]
ok，谢谢，我看看，因为一般要非常用地区登录才有验证码，本来是想加的，一直没机会。。。

**Comment by CharlesPikachu** [comment]
多谢，现在的版本已经加了你说的内容，因为要统一一下格式方便以后改，所以就没有merge你的pull，在readme里添加关于你的致谢好了QAQ。

**Comment by skygongque** [comment]
一开始我只是想用大佬你的代码练习的，所以自己重写了一遍(把原有结构都该掉了)，后来因为验证码的问题无法登录我自己加了一个手动输入，pull requests只是为了把代码给你，没想着接受的，还麻烦你改回原来的结构，最后还得了个致谢，受宠若惊，谢谢
