### ISSUE TITLE
微博RuntimeError: 系统错误，请稍后再试

### ISSUE THREAD

**Issue by dearCorazon** [CharlesPikachu/DecryptLogin#10]
请问具体是什么错误呢   ？（2020.3.30）

**Comment by CharlesPikachu** [comment]
这是微博提供的错误信息，之前也有几个人反应过，好像过段时间/换个网络就好了，具体我也不知道他们是怎么解决的，没有收到过反馈，我这测试一直是正常的。你解决的话可以说下如何解决的，我在readme里标一下。

**Comment by yourgood** [comment]
我也出现这个错误  太难了

**Comment by Jepson-Song** [comment]
我也遇到“系统错误，请稍后再试了”

**Comment by CharlesPikachu** [comment]
应该是异地登录，需要验证的缘故，在对应电脑的浏览器里登录几次移动端试试，看看验证还在不在，不在就可以正常使用了

**Comment by Jepson-Song** [comment]
> 应该是异地登录，需要验证的缘故，在对应电脑的浏览器里登录几次移动端试试，看看验证还在不在，不在就可以正常使用了

ssh登陆远程服务器怎么办呢？没浏览器啊...

**Comment by CharlesPikachu** [comment]
现在可以用mobile模式登录/扫码登录，应该就没有这个问题了
