### ISSUE TITLE
微博监控，首次运行只获得首页的前十条作为weibo_ids的池子而不是所有微博是吗？

### ISSUE THREAD

**Issue by lipeng-coding** [CharlesPikachu/DecryptLogin#11]
微博监控，首次运行只获得首页的前十条作为weibo_ids的池子而不是所有微博是吗？
在下面首次获取cards的时候我做了一次打印只有10条
`def __monitor(self, user_id, profile_url):
		user_name, containerid = self.__getContainerid(user_id, profile_url)
		res = self.session.get(self.api_url.format(user_id, user_id, containerid))
		weibo_ids = []
		cards = res.json()['data']['cards']
		print('num:',len(cards))
		for card in cards:
			if card['card_type'] == 9:
				weibo_ids.append(str(card['mblog']['id']))
		while True:
			weibo_ids = self.__checkUpdate(user_id, profile_url, weibo_ids)
			time.sleep(self.time_interval)`

**Comment by CharlesPikachu** [comment]
只是监控一下对方是否有新的微博，这样做已经足够了。
