### ISSUE TITLE
b站指定up主下载视频不全

### ISSUE THREAD

**Issue by qizidog** [CharlesPikachu/DecryptLogin#22]
> 老哥你是真的猛，但是我在使用您的工具下载b站指定up主视频时，获取视频的总数目为该up主的投稿数量。

> 其实我是想用来爬教学课程，避免被下架后看不了的~~，存在一个视频集由几十个视频组成的情况，但借助该工具下载时，默认只会下载视频集的第一个视频，剩下的视频没有做处理。

> 本来想自己调试好的，但是能力有限，downloadUserVideos.py文件的__downloadVideos方法中相关内容期待老哥能够补全一下，感激不尽！

**Comment by qizidog** [comment]
keypoint 在于获取同一视频集中其他视频的aid

**Comment by shaolin-kongfu** [comment]
> keypoint 在于获取同一视频集中其他视频的aid

同一视频集的aid都是相同的，不同的应该是cid,你可以参考一下
https://github.com/Henryhaohao/Bilibili_video_download
这个大佬的下载助手可以分P下载

**Comment by qizidog** [comment]
感谢感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CharlesPikachu/DecryptLogin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月10日(星期五) 下午5:16
收件人:&nbsp;"CharlesPikachu/DecryptLogin"<DecryptLogin@noreply.github.com&gt;;
抄送:&nbsp;"451559450"<451559450@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CharlesPikachu/DecryptLogin] b站指定up主下载视频不全 (#22)





  
keypoint 在于获取同一视频集中其他视频的aid
  
同一视频集的aid都是相同的，不同的应该是cid,你可以参考一下
 https://github.com/Henryhaohao/Bilibili_video_download
 这个大佬的下载助手可以分P下载
