### ISSUE TITLE
get twitter "authenticity_token"  failed

### ISSUE THREAD

**Issue by fishmisswater** [CharlesPikachu/DecryptLogin#23]

**Comment by CharlesPikachu** [comment]
you have to ensure that your network could visit https://twitter.com/

**Comment by fishmisswater** [comment]
> you have to ensure that your network could visit https://twitter.com/
哈哈，刚看到你是华人。twitter的登录接口已经改变了。目前无法直接拿到authenticity_token。我这边测试用某些UA，例如“Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; chromeframe/11.0.696.57)”，打开首页可以得到一个手机端cookie（不知道twitter为什么把请求标志成手机登录），其中有个“_mb_tk”字段，可以代替authenticity_token，登录成功后跳转到mobiel.twitter.com。logged_in等字段再拿着session用高版本UA打开www.twitter.com即可

**Comment by CharlesPikachu** [comment]
the latest version(0.1.32) has fixed this issue
