### ISSUE TITLE
weibo监控的一个建议

### ISSUE THREAD

**Issue by 1148270327** [CharlesPikachu/DecryptLogin#28]
感谢大佬代码，我在你的基础上添加了同时监控多名博主的微博，运行一段时间后就是无法运行了，cookies一直报list out of range, 但浏览器能打开，不知是不是程序重启后，登录的cookies没有重置呀？
另外，有个建议，就是要实现多博主监控，可以通过登录用户关注多名博主，然后检测登录用户主页最新微博，就能刷到所有关注的博主动态啦。这样可以降低爬虫爬取多名博主页面的问题。

**Comment by 1148270327** [comment]
另外，微博登录分pc和mobile, 这里的mobile是指微博app吗，还是手机浏览器h5? 想知道大佬抓包的对象

**Comment by CharlesPikachu** [comment]
你可以自行更改，这只是为了说明DecryptLogin包用处的一个简单使用案例，我并不打算一直维护优化。

一个是m.weibo.cn 一个是weibo.com
