### ISSUE TITLE
bilibili app login error

### ISSUE THREAD

**Issue by Hitchcock717** [CharlesPikachu/DecryptLogin#30]
traceback {'code': -449, 'message': '服务繁忙, 请稍后再试', 'ts': 159546****}

**Comment by CharlesPikachu** [comment]
try this:
```python
from DecryptLogin import login  

lg = login.Login()   
infos_return, session = lg.bilibili(username, password, 'pc')
```
I will try to fix the mobile mode error when time free

**Comment by CharlesPikachu** [comment]
My login test seems to be fine when using mobile mode today, so close this issue.
