### ISSUE TITLE
Bilibili登录时出现“服务繁忙，请稍后重试”

### ISSUE THREAD

**Issue by Shadyree** [CharlesPikachu/DecryptLogin#32]
你好，我在登陆bilibili时，刚开始的时候可以正常登录，成功一两次后再登录就会出现Runtime Error:服务繁忙，请稍后重试。这是bilibili的防范措施吗？我在网上搜了其他人的解决方案还是解决不了，请问有什么措施吗？

**Comment by Shadyree** [comment]
有看到有人写是登录接口有问题，但是没有解决方法，也有看到有人说10min后重试

**Comment by CharlesPikachu** [comment]
尝试一下`mode='pc'`

**Comment by Shadyree** [comment]
谢谢，换了以后就可以登陆，如果还有问题，可以mobile和pc换着试试
