### ISSUE TITLE
在关注列表中选择监控用户后大概两分钟左右会报错（微博）

### ISSUE THREAD

**Issue by wstianyi** [CharlesPikachu/DecryptLogin#33]
1-> 我设置的时间间隔3S，在运行大概2分钟左右时会报错。
cards = res.json()['data']['cards']
‘KeyError: 'data'’
2 -> 重新执行无法显示关注列表。显示如下：
‘’未指定想要监控的用户ID, 您关注的用户有:
(是否想选择其中一位进行监控?)
----------------------------------------
----------------------------------------
请选择您想要监控的用户编号(例如1):‘’

**Comment by CharlesPikachu** [comment]
这只是一个简单的DecryptLogin应用案例，我并不打算优化。

应该是因为抓取太频繁了，建议尝试使用比较大且随机的时间间隔
