### ISSUE TITLE
Bilibili登陆问题

### ISSUE THREAD

**Issue by Shadyree** [CharlesPikachu/DecryptLogin#34]
在登陆时，出现了can only concatenate str (not "bytes") to str报错，调试发现是bilibili.py的107行，因为登陆需要验证码，在第二次运行到这里的时候，password的类型从str变为了bytes。

转换后又出现了
OverflowError:191 bytes needed for message, but there is only space for 117的报错

暂未解决

**Comment by Shadyree** [comment]
我使用的python版本是3.8.5

**Comment by Shadyree** [comment]
又调试了一下发现它的验证码是字母，但是我去b站登陆是点击对应文字，会不会是这个原因？

**Comment by CharlesPikachu** [comment]
So why do you login in bilibili so frequently?

**Comment by Shadyree** [comment]
哦哦，这只是用来模拟登陆吧，我本来想来爬一爬壁纸的。
