### ISSUE TITLE
微博无法登陆了

### ISSUE THREAD

**Issue by ymilv** [CharlesPikachu/DecryptLogin#35]
使用weibo(username, password, 'mobile')登录，会提示“RuntimeError: login second verify”
浏览器中登录发现，m.weibo.cn登录需要验证手机短信，应该是微博手机版登录机制修改了。
希望有办法解决，谢谢。

**Comment by CharlesPikachu** [comment]
新版本已经修复了该问题~你可以试试，不过短信验证码部分没有测试，所以可能会有点问题，在后续的版本会测试一下mobile端的短信验证功能（因为现在我的账号好像受限制了，之后解除限制了我再测试），目前你可以暂时使用扫码登录

**Comment by CharlesPikachu** [comment]
new version is published, so I closed this issue.

feel free to reopen this issue if you have any questions about this issue again.
