### ISSUE TITLE
微博PC端登录失败

### ISSUE THREAD

**Issue by holll** [CharlesPikachu/DecryptLogin#37]
res_json的值为{'retcode': 0, 'msg': 'system error', 'exectime': 2}
感觉是微博强制开启了登录扫码验证

**Comment by philohistoria** [comment]
类似的错误

**Comment by jpdong** [comment]
感觉可以直接做成扫码登录，免去了各种安全验证的问题

**Comment by CharlesPikachu** [comment]
sry，最近比较忙，我周末的时候看看什么情况，fix一下这个问题。

**Comment by zhangjingfeng520** [comment]
> sry，最近比较忙，我周末的时候看看什么情况，fix一下这个问题。

请问还会修复吗？

**Comment by hnlyj** [comment]
请问还修复吗

**Comment by CharlesPikachu** [comment]
会的，正在重构新的code，而且需要修复的平台比较多～预计这两周会push新的version

**Comment by CharlesPikachu** [comment]
https://www.zhihu.com/question/417862407 应该是微博的问题，暂时解决不了，新版本今天整体测试完之后会push上来，到时候选择scanqr模式登录吧，pc模式怕是不行了

**Comment by holll** [comment]
不管什么模式，能登录就很满足了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "CharlesPikachu"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 晚上8:02
收件人: "CharlesPikachu/DecryptLogin"<DecryptLogin@noreply.github.com&gt;; 
抄送: "奈陌"<380460708@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CharlesPikachu/DecryptLogin] 微博PC端登录失败 (#37)





 
https://www.zhihu.com/question/417862407 应该是微博的问题，暂时解决不了，新版本今天整体测试完之后会push上来，到时候选择scanqr模式登录吧，pc模式怕是不行了
 
&mdash;

**Comment by CharlesPikachu** [comment]
weibo.py里的code其实已经可以登录了，只不过我还没整体测试完，你要急的话可以直接用，稍微改下就行，晚点我会上传到pypi~

**Comment by CharlesPikachu** [comment]
new version is published, so I closed this issue.

feel free to reopen this issue if you have any questions about this issue again.
