### ISSUE TITLE
知乎手机号登录失败

### ISSUE THREAD

**Issue by FrazierLei** [CharlesPikachu/DecryptLogin#46]
错误信息：{'message': '为了您的帐号安全，请使用短信验证码登录', 'code': 120017} 登录失败

**Comment by CharlesPikachu** [comment]
用户名改成自己绑定的邮箱，错误是知乎系统问题，我这边解决不了，你在网页上登录也会有这个提示

**Comment by FrazierLei** [comment]
成功了，非常感谢！
