### ISSUE TITLE
12306的例子跑不起来

### ISSUE THREAD

**Issue by xiangrong2017** [CharlesPikachu/DecryptLogin#47]
def cracker(imagepath):
    # 打开验证码图片
    img = Image.open(imagepath)
    # 识别验证码图片
    result = IdentifyAPI(img)
    # 返回识别结果(百度网盘为数字验证码)
    return result

这个IdentifyAPI未定义？

**Comment by CharlesPikachu** [comment]
这只是一个示例代码，教你如何自定义一个函数来识别验证码，从而无需人工识别输入，并不是一个完整可运行的Demo，IdentifyAPI需要你自己定义
