### ISSUE TITLE
网易云音乐报错

### ISSUE THREAD

**Issue by SlowFlight** [CharlesPikachu/DecryptLogin#5]
music163.py 119 login
raise RuntimeError(res_json.get('msg')) if 'msg' in res_json else RuntimeError(r
es_json.get('message'))

RuntimeError:
Cheating
这是检测出来作弊了？

**Comment by CharlesPikachu** [comment]
... 你试试把网易云里的设备认证之类的东西先关掉~

**Comment by SlowFlight** [comment]
登录保护是关的……
但是用邮箱不行，换成手机号就能登陆了
