### ISSUE TITLE
TB的那个例子，我爬成功了一次，然后就再也爬不到数据了，每次都只能爬到0条

### ISSUE THREAD

**Issue by xiaohaoxiang** [CharlesPikachu/DecryptLogin#50]
成功的那次爬到了大概几千条数据吧

**Comment by CharlesPikachu** [comment]
应该是因为太频繁所以被封了，换个设备就又可以运行了。。。你可以自己测试一下，应该是因为翻页需要验证码的原因。

**Comment by make-process-everyday** [comment]
我爬取的淘宝的数据，第一次成功，后面每次都是0条。我测试了下，扫描登录是正常的，自己用网页访问是正常的。过了几小时后发现确实被封导致的。
