### ISSUE TITLE
 ”Fail to login, your account requires security verification“

### ISSUE THREAD

**Issue by pengber** [CharlesPikachu/DecryptLogin#52]
当我是用淘宝demo爬取数据时，链接https://github.com/CharlesPikachu/DecryptLogin/tree/master/examples/tbgoods ，扫码后报错“ Fail to login, your account requires security verification”，自己在web网页扫码可以登陆，请问是哪里的问题

**Comment by CharlesPikachu** [comment]
我这边测试没问题。。。需要安全验证，应该是淘宝的问题
