### ISSUE TITLE
百度贴吧模拟登录相关问题

### ISSUE THREAD

**Issue by lc6464** [CharlesPikachu/DecryptLogin#54]
扫描二维码登录时若网页提醒需要验证（比如说使用密码登录时由于各种原因需要验证码验证），程序会直接报错并退出。
猜测问题出在 `/DecryptLogin/core/baidutieba.py : 78`
而且报错后二维码并不会被删除。
提醒需要验证时报错我并不知道如何解决，报错删除二维码的话在第78行之前增加一个 `removeImage(os.path.join(self.cur_path, 'qrcode.jpg'))` 即可。

**Comment by lc6464** [comment]
`params` 中的 `'_': timestamp` 也是不需要的，如果你的源代码是通过分析网络请求获得的，`_` 也许只是百度的网页中的 jQuery Ajax 中配置了 `cache: false` 才导致自动添加这个参数的。

**Comment by CharlesPikachu** [comment]
useless report

**Comment by lc6464** [comment]
**扫描二维码登录时若网页提醒需要验证（比如说使用密码登录时由于各种原因需要验证码验证），程序会直接报错并退出。
而且报错后二维码并不会被删除。**
