### ISSUE TITLE
微博登录验证码输入问题

### ISSUE THREAD

**Issue by ylh23y** [CharlesPikachu/DecryptLogin#59]
from DecryptLogin import login
'''微博模拟登录'''
def login(username, password):
    lg = login.Login()
    infos_return, session = lg.weibo(username, password, 'pc')
    return infos_return, session

我通过pc验证码登录，请问验证码是放在那里，只能每次乱输入一个验证码就报错
![211](https://user-images.githubusercontent.com/13464610/119589844-3bf62380-be06-11eb-9bef-167de7ec679f.png)

**Comment by CharlesPikachu** [comment]
代码不是这么写的...你函数定义的名字和导入的库的login重复导致被覆盖了，所以报错function没有login属性

**Comment by ylh23y** [comment]
函数改了还是报错，mode改成 mobile和scanqr可以正常的登录
![搜狗截图20210528114501](https://user-images.githubusercontent.com/13464610/119926642-536e1180-bfaa-11eb-829f-732df2fbe117.png)
![117](https://user-images.githubusercontent.com/13464610/119926818-acd64080-bfaa-11eb-9dc8-f277cefdcb70.png)
