### ISSUE TITLE
微博 pc 端登录问题

### ISSUE THREAD

**Issue by 951409031** [CharlesPikachu/DecryptLogin#61]
微博 PC 端目前登录好像需要扫码登录, 有解决办法吗
![image](https://user-images.githubusercontent.com/44198346/120446345-0b8d2700-c3bc-11eb-93f8-ecf794fa7d56.png)
实现类似于接打码平台一样的自动化
现在通过扫码解决的话, 长时间运行不是很方便

**Comment by rufeng-h** [comment]
微博不提供直接用户名密码登录了，要么扫码，要么手机验证码

**Comment by CharlesPikachu** [comment]
微博的问题。。。我也没法解决。。。现在最新版本默认使用的扫码登录。

**Comment by CharlesPikachu** [comment]
目前已经支持二维码登录和手机验证码登录~
