### ISSUE TITLE
是否支持腾讯游戏网站的登陆。

### ISSUE THREAD

**Issue by jingyugao** [CharlesPikachu/DecryptLogin#71]
比如
https://dnf.qq.com/comm-htdocs/milo_mobile/login.html?s_url=https%3A%2F%2Fsg.qq.com%2Fcp%2Fa20200228signin%2Findex.html&sData=&logo=

**Comment by MaoSource** [comment]
> 比如 https://dnf.qq.com/comm-htdocs/milo_mobile/login.html?s_url=https%3A%2F%2Fsg.qq.com%2Fcp%2Fa20200228signin%2Findex.html&sData=&logo=

我也在找这种

**Comment by CharlesPikachu** [comment]
带滑块验证码的可以用类似selenium这样的工具来实现模拟登录，否则requests实现起来太复杂了。
