### ISSUE TITLE
淘宝的“安全验证”

### ISSUE THREAD

**Issue by AEFR-SC** [CharlesPikachu/DecryptLogin#72]
用手机扫描二维码登录淘宝后，报RuntimeError:Fail to login, your account requires security verification.
我在淘宝里找了半天设置也没有找到类似的“安全验证”

**Comment by AmazingXiaomi** [comment]
+1

**Comment by CharlesPikachu** [comment]
确认自己已经关闭了安全验证，然后把decryptlogin升级到最新的版本即可。。。我刚刚更新了一版。。。
