### ISSUE TITLE
taobaosnap.py 用不了了

### ISSUE THREAD

**Issue by cappuccino8** [CharlesPikachu/DecryptLogin#73]
购买商品这块 失败，然后就一直卡死，也没提示
![d9e16b6544dc1f4208e814dd5b7013f](https://user-images.githubusercontent.com/27793729/153560669-5e695f3f-a725-45e4-8aa4-fef22af5b544.png)

**Comment by CharlesPikachu** [comment]
清空购物车只添加一个商品试试。我这边自己测试没问题，这只是一个python爬虫学习案例，我不打算写的太好，容易被倒卖和恶意使用，比如购物车里有一家店铺的两个商品返回的内容是不一样的，我没有写这块内容，希望理解，谢谢
