### ISSUE TITLE
购买商品响应值不正确，tb封了吗

### ISSUE THREAD

**Issue by AngryBigCat** [CharlesPikachu/DecryptLogin#75]
https://github.com/CharlesPikachu/DecryptLogin/blob/aab2698a44f004a6551708c13608c24941ee7a06/examples/taobaosnap/taobaosnap.py#L139

**Comment by AngryBigCat** [comment]
'NoneType' object has no attribute 'group'

**Comment by AngryBigCat** [comment]
![image](https://user-images.githubusercontent.com/14774417/153797851-03ae83ab-f7cd-43f2-925f-7780b6f04ad5.png)

**Comment by hacvk** [comment]
你好，环智中诚现在啥情况了啊，什么时候恢复啊

**Comment by AngryBigCat** [comment]
> 你好，环智中诚现在啥情况了啊，什么时候恢复啊

在这问不合适
