### ISSUE TITLE
淘宝登陆成功后日志显示失败

### ISSUE THREAD

**Issue by javajiang** [CharlesPikachu/DecryptLogin#8]
淘宝登陆成功后日志显示Fail to login, qrcode has expired...而且有个问题想咨询下，如果我想爬虫，该如何接管登陆后的淘宝

**Comment by CharlesPikachu** [comment]
错误提示表明二维码过期了，我这测试了一下，扫码后是可以正常登录的，所以不知道你是什么情况，爬虫只需要使用登录后返回的session请求需要爬取的目标链接即可。

**Comment by javajiang** [comment]
大佬好：
扫码后确实能够登陆，但是登陆后ide没有返回session，而且登陆成功后过一会就会提示Fail to login, qrcode has expired...。还想请教下大佬，怎么使用session去爬虫，小白刚学




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CharlesPikachu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 晚上10:07
收件人:&nbsp;"CharlesPikachu/DecryptLogin"<DecryptLogin@noreply.github.com&gt;;
抄送:&nbsp;"未名"<2406761970@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CharlesPikachu/DecryptLogin] 淘宝登陆成功后日志显示失败 (#8)





 
错误提示表明二维码过期了，我这测试了一下，扫码后是可以正常登录的，所以不知道你是什么情况，爬虫只需要使用登录后返回的session请求需要爬取的目标链接即可。
