### ISSUE TITLE
[BUG]京东模拟登录失效

### ISSUE THREAD

**Issue by Dimlitter** [CharlesPikachu/DecryptLogin#80]
**Environment (使用环境)**
powershell
- Installation method (安装方式): pip install
- The version of DecryptLogin (版本号): 最新版
- Operating system (操作系统): windows 10
- Python version (Python版本): 3.9.7

**Question description (问题描述)**
模拟登录时发生错误如下
发生异常: SSLError
HTTPSConnectionPool(host='qr.m.jd.com', port=443): Max retries exceeded with url: /check?callback=a&isNewVersion=1&_format_=json&appid=133&token=w148mf7tn9zzqmqnenvq25141zf6pnsm (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Screenshot (报错截图)**
![image](https://user-images.githubusercontent.com/68945228/161430081-16962e33-0d94-42d6-966e-b2e0feeb93ee.png)

**Advice (修复建议)**
经测试，更换UA能暂时解决这一问题。但是登录几次后问题复现。疑似京东对requset headers检查趋向严格，建议完善headers或增加随机UA？

**Comment by CharlesPikachu** [comment]
建议使用client类进行模拟登录，避免频繁登录的问题。
