### ISSUE TITLE
[Taobao 启用脚本才能显示当前页面]

### ISSUE THREAD

**Issue by SimonCK666** [CharlesPikachu/DecryptLogin#84]
**Environment python3.6**

- Installation method (安装方式): pip install DecryptLogin 
- The version of DecryptLogin (版本号): 0.3.6
- Operating system (操作系统): Windows10
- Python version (Python版本): python3.6

**Question description (问题描述)**
TaoBao 登录之后出现 [启用脚本才能显示当前页面]

**Screenshot (报错截图)**
![image](https://user-images.githubusercontent.com/57851315/168252353-f2b0d324-01c9-454c-b8bb-9d8e0a6b63cd.png)
![image](https://user-images.githubusercontent.com/57851315/168252495-64953971-9aa7-4e5b-bfb9-77a0d16eab02.png)

**Advice (修复建议)**
增加脚本反爬，显示response信息

**Comment by CharlesPikachu** [comment]
最新的脚本已经修复，相关使用文档稍后更新
