### ISSUE TITLE
网易云音乐登陆总是显示RuntimeError: 网络太拥挤，请稍候再试。

### ISSUE THREAD

**Issue by mcc-devel** [CharlesPikachu/DecryptLogin#86]
**Environment (使用环境)**

- Installation method (安装方式):  Pip 22.2.2
- The version of DecryptLogin (版本号):  0.3.8
- Operating system (操作系统): macOS Big Sur
- Python version (Python版本): Python 3.10.5

**Question description (问题描述)**
网易云音乐登陆总是显示RuntimeError: 网络太拥挤，请稍候再试。

**Screenshot (报错截图)**
<img width="1440" alt="截屏2022-08-16 17 52 18" src="https://user-images.githubusercontent.com/74864408/184851222-c27304b7-ebe0-4977-b647-1353d4ef3edc.png">

**Advice (修复建议)**
??? 更改UA？cookies？

**P.S.（注）**
<img width="1440" alt="截屏2022-08-16 17 54 15" src="https://user-images.githubusercontent.com/74864408/184851776-dc3007cb-fe8b-4124-b98d-77274501e9b6.png">
根据[#83](https://github.com/CharlesPikachu/DecryptLogin/issues/83)
使用scanqr模式依然不行

close是手滑了

**Comment by CharlesPikachu** [comment]
可能是因为挂了vpn或者不是在常用网络，我晚点会push一个solution上来

**Comment by CharlesPikachu** [comment]
你可以尝试一下：

`pip install DecryptLogin==0.3.9`

然后先用pc模式登录，会提示你需要短信验证：

```python
from DecryptLogin import login

lg = login.Login()
infos_return, session = lg.music163(username, password, 'pc')
```

之后再用扫码登录就不会报错了应该：

```python
from DecryptLogin import login

lg = login.Login()
infos_return, session = lg.music163('', '', 'scanqr')
```
