### ISSUE TITLE
知乎提示-----登录次数过多

### ISSUE THREAD

**Issue by jspenliany** [CharlesPikachu/DecryptLogin#9]
你好，请问我下载代码使用了新手教程里面的代码编了简单的登录脚本。但是执行之后提示

DecryptLogin\platforms\zhihu.py", line 573, in login
    raise RuntimeError(res_json.get('error').get('message'))
RuntimeError: 登录过于频繁，请稍后重试，或者联系 antispam@zhihu.com

上述提示信息是否意味着被识别了？如何解决

**Comment by CharlesPikachu** [comment]
就是字面意思，登录太频繁了，你可以把cookies保存下来，等会话过期了再重新登录。。。你这个过段时间等他自己好吧只能

**Comment by CharlesPikachu** [comment]
前几天比较忙，今天我测试了一下，发现确实存在你说的问题。盲猜是前几天知乎服务器崩了几次之后导致的该错误。
我待会会对代码进行更新，以解决该问题。上传代码之后该issue会自动关闭。
